// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// makegkPointcpp
Rcpp::NumericVector makegkPointcpp(int grain, int ncores, Rcpp::NumericMatrix& gsbval, Rcpp::NumericMatrix& dist2);
RcppExport SEXP _leaktest_makegkPointcpp(SEXP grainSEXP, SEXP ncoresSEXP, SEXP gsbvalSEXP, SEXP dist2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type grain(grainSEXP);
    Rcpp::traits::input_parameter< int >::type ncores(ncoresSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type gsbval(gsbvalSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type dist2(dist2SEXP);
    rcpp_result_gen = Rcpp::wrap(makegkPointcpp(grain, ncores, gsbval, dist2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_leaktest_makegkPointcpp", (DL_FUNC) &_leaktest_makegkPointcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_leaktest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
