# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makegkPointcpp <- function(grain, ncores, gsbval, dist2) {
    .Call('_leaktest_makegkPointcpp', PACKAGE = 'leaktest', grain, ncores, gsbval, dist2)
}

